//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVSWeb_Cloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int qsId { get; set; }
        public string qsTitle { get; set; }
        public string qsContent { get; set; }
    }
}
